
//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated (07/15/2021 00:38:40 UTC) by the following tool:
//        https://github.com/lithiumtoast/c2cs (v0.0.0.0)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using C2CS;

#nullable enable
#pragma warning disable 1591

public static unsafe partial class uv
{
    private const string LibraryName = "uv";

    // Function @ uv.h:1814:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_loop_set_data(uv_loop_t* param, void* data);

    // Function @ uv.h:1813:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void* uv_loop_get_data(uv_loop_t* param);

    // Function @ uv.h:1782:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_thread_equal(uv_thread_t* t1, uv_thread_t* t2);

    // Function @ uv.h:1781:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_thread_join(uv_thread_t* tid);

    // Function @ uv.h:1780:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_thread_t uv_thread_self();

    // Function @ uv.h:1776:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_thread_create_ex(uv_thread_t* tid, uv_thread_options_t* @params, uv_thread_cb entry, void* arg);

    // Function @ uv.h:1761:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_thread_create(uv_thread_t* tid, uv_thread_cb entry, void* arg);

    // Function @ uv.h:1757:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_gettimeofday(uv_timeval64_t* tv);

    // Function @ uv.h:1755:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_key_set(uv_key_t* key, void* value);

    // Function @ uv.h:1754:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void* uv_key_get(uv_key_t* key);

    // Function @ uv.h:1753:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_key_delete(uv_key_t* key);

    // Function @ uv.h:1752:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_key_create(uv_key_t* key);

    // Function @ uv.h:1750:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_once(uv_once_t* guard, FnPtr_UV_Void callback);

    // Function @ uv.h:1746:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_cond_timedwait(uv_cond_t* cond, uv_mutex_t* mutex, ulong timeout);

    // Function @ uv.h:1745:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_cond_wait(uv_cond_t* cond, uv_mutex_t* mutex);

    // Function @ uv.h:1743:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_barrier_wait(uv_barrier_t* barrier);

    // Function @ uv.h:1742:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_barrier_destroy(uv_barrier_t* barrier);

    // Function @ uv.h:1741:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_barrier_init(uv_barrier_t* barrier, uint count);

    // Function @ uv.h:1739:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_cond_broadcast(uv_cond_t* cond);

    // Function @ uv.h:1738:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_cond_signal(uv_cond_t* cond);

    // Function @ uv.h:1737:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_cond_destroy(uv_cond_t* cond);

    // Function @ uv.h:1736:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_cond_init(uv_cond_t* cond);

    // Function @ uv.h:1734:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_sem_trywait(uv_sem_t* sem);

    // Function @ uv.h:1733:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_sem_wait(uv_sem_t* sem);

    // Function @ uv.h:1732:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_sem_post(uv_sem_t* sem);

    // Function @ uv.h:1731:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_sem_destroy(uv_sem_t* sem);

    // Function @ uv.h:1730:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_sem_init(uv_sem_t* sem, uint value);

    // Function @ uv.h:1728:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_rwlock_wrunlock(uv_rwlock_t* rwlock);

    // Function @ uv.h:1727:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_rwlock_trywrlock(uv_rwlock_t* rwlock);

    // Function @ uv.h:1726:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_rwlock_wrlock(uv_rwlock_t* rwlock);

    // Function @ uv.h:1725:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_rwlock_rdunlock(uv_rwlock_t* rwlock);

    // Function @ uv.h:1724:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_rwlock_tryrdlock(uv_rwlock_t* rwlock);

    // Function @ uv.h:1723:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_rwlock_rdlock(uv_rwlock_t* rwlock);

    // Function @ uv.h:1722:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_rwlock_destroy(uv_rwlock_t* rwlock);

    // Function @ uv.h:1721:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_rwlock_init(uv_rwlock_t* rwlock);

    // Function @ uv.h:1719:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_mutex_unlock(uv_mutex_t* handle);

    // Function @ uv.h:1718:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_mutex_trylock(uv_mutex_t* handle);

    // Function @ uv.h:1717:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_mutex_lock(uv_mutex_t* handle);

    // Function @ uv.h:1716:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_mutex_destroy(uv_mutex_t* handle);

    // Function @ uv.h:1715:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_mutex_init_recursive(uv_mutex_t* handle);

    // Function @ uv.h:1714:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_mutex_init(uv_mutex_t* handle);

    // Function @ uv.h:1712:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString uv_dlerror(uv_lib_t* lib);

    // Function @ uv.h:1711:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_dlsym(uv_lib_t* lib, CString name, void** ptr);

    // Function @ uv.h:1710:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_dlclose(uv_lib_t* lib);

    // Function @ uv.h:1709:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_dlopen(CString filename, uv_lib_t* lib);

    // Function @ uv.h:1707:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_disable_stdio_inheritance();

    // Function @ uv.h:1705:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_sleep(uint msec);

    // Function @ uv.h:1704:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern ulong uv_hrtime();

    // Function @ uv.h:1702:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern ulong uv_get_constrained_memory();

    // Function @ uv.h:1701:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern ulong uv_get_total_memory();

    // Function @ uv.h:1700:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern ulong uv_get_free_memory();

    // Function @ uv.h:1698:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_chdir(CString dir);

    // Function @ uv.h:1696:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_cwd(CString buffer, uint* size);

    // Function @ uv.h:1694:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_exepath(CString buffer, uint* size);

    // Function @ uv.h:1690:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_if_indextoiid(uint ifindex, CString buffer, uint* size);

    // Function @ uv.h:1687:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_if_indextoname(uint ifindex, CString buffer, uint* size);

    // Function @ uv.h:1672:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_random(uv_loop_t* loop, uv_random_t* req, void* buf, uint buflen, uint flags, uv_random_cb cb);

    // Function @ uv.h:1657:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_inet_pton(int af, CString src, void* dst);

    // Function @ uv.h:1656:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_inet_ntop(int af, void* src, CString dst, uint size);

    // Function @ uv.h:1654:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_ip6_name(sockaddr_in6* src, CString dst, uint size);

    // Function @ uv.h:1653:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_ip4_name(sockaddr_in* src, CString dst, uint size);

    // Function @ uv.h:1651:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_ip6_addr(CString ip, int port, sockaddr_in6* addr);

    // Function @ uv.h:1650:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_ip4_addr(CString ip, int port, sockaddr_in* addr);

    // Function @ uv.h:1646:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_event_getpath(uv_fs_event_t* handle, CString buffer, uint* size);

    // Function @ uv.h:1645:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_event_stop(uv_fs_event_t* handle);

    // Function @ uv.h:1641:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_event_start(uv_fs_event_t* handle, uv_fs_event_cb cb, CString path, uint flags);

    // Function @ uv.h:1640:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_event_init(uv_loop_t* loop, uv_fs_event_t* handle);

    // Function @ uv.h:1606:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_loadavg(double* avg);

    // Function @ uv.h:1604:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_signal_stop(uv_signal_t* handle);

    // Function @ uv.h:1601:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_signal_start_oneshot(uv_signal_t* handle, uv_signal_cb signal_cb, int signum);

    // Function @ uv.h:1598:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_signal_start(uv_signal_t* handle, uv_signal_cb signal_cb, int signum);

    // Function @ uv.h:1597:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_signal_init(uv_loop_t* loop, uv_signal_t* handle);

    // Function @ uv.h:1585:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_poll_getpath(uv_fs_poll_t* handle, CString buffer, uint* size);

    // Function @ uv.h:1584:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_poll_stop(uv_fs_poll_t* handle);

    // Function @ uv.h:1580:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_poll_start(uv_fs_poll_t* handle, uv_fs_poll_cb poll_cb, CString path, uint interval);

    // Function @ uv.h:1579:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_poll_init(uv_loop_t* loop, uv_fs_poll_t* handle);

    // Function @ uv.h:1550:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_statfs(uv_loop_t* loop, uv_fs_t* req, CString path, uv_fs_cb cb);

    // Function @ uv.h:1544:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_lchown(uv_loop_t* loop, uv_fs_t* req, CString path, uv_uid_t uid, uv_gid_t gid, uv_fs_cb cb);

    // Function @ uv.h:1538:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_fchown(uv_loop_t* loop, uv_fs_t* req, uv_file file, uv_uid_t uid, uv_gid_t gid, uv_fs_cb cb);

    // Function @ uv.h:1532:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_chown(uv_loop_t* loop, uv_fs_t* req, CString path, uv_uid_t uid, uv_gid_t gid, uv_fs_cb cb);

    // Function @ uv.h:1527:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_fchmod(uv_loop_t* loop, uv_fs_t* req, uv_file file, int mode, uv_fs_cb cb);

    // Function @ uv.h:1523:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_realpath(uv_loop_t* loop, uv_fs_t* req, CString path, uv_fs_cb cb);

    // Function @ uv.h:1519:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_readlink(uv_loop_t* loop, uv_fs_t* req, CString path, uv_fs_cb cb);

    // Function @ uv.h:1513:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_symlink(uv_loop_t* loop, uv_fs_t* req, CString path, CString new_path, int flags, uv_fs_cb cb);

    // Function @ uv.h:1495:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_link(uv_loop_t* loop, uv_fs_t* req, CString path, CString new_path, uv_fs_cb cb);

    // Function @ uv.h:1491:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_lstat(uv_loop_t* loop, uv_fs_t* req, CString path, uv_fs_cb cb);

    // Function @ uv.h:1485:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_lutime(uv_loop_t* loop, uv_fs_t* req, CString path, double atime, double mtime, uv_fs_cb cb);

    // Function @ uv.h:1479:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_futime(uv_loop_t* loop, uv_fs_t* req, uv_file file, double atime, double mtime, uv_fs_cb cb);

    // Function @ uv.h:1473:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_utime(uv_loop_t* loop, uv_fs_t* req, CString path, double atime, double mtime, uv_fs_cb cb);

    // Function @ uv.h:1468:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_chmod(uv_loop_t* loop, uv_fs_t* req, CString path, int mode, uv_fs_cb cb);

    // Function @ uv.h:1463:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_access(uv_loop_t* loop, uv_fs_t* req, CString path, int mode, uv_fs_cb cb);

    // Function @ uv.h:1456:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_sendfile(uv_loop_t* loop, uv_fs_t* req, uv_file out_fd, uv_file in_fd, long in_offset, uint length, uv_fs_cb cb);

    // Function @ uv.h:1451:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_ftruncate(uv_loop_t* loop, uv_fs_t* req, uv_file file, long offset, uv_fs_cb cb);

    // Function @ uv.h:1447:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_fdatasync(uv_loop_t* loop, uv_fs_t* req, uv_file file, uv_fs_cb cb);

    // Function @ uv.h:1443:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_fsync(uv_loop_t* loop, uv_fs_t* req, uv_file file, uv_fs_cb cb);

    // Function @ uv.h:1438:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_rename(uv_loop_t* loop, uv_fs_t* req, CString path, CString new_path, uv_fs_cb cb);

    // Function @ uv.h:1434:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_fstat(uv_loop_t* loop, uv_fs_t* req, uv_file file, uv_fs_cb cb);

    // Function @ uv.h:1430:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_stat(uv_loop_t* loop, uv_fs_t* req, CString path, uv_fs_cb cb);

    // Function @ uv.h:1426:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_closedir(uv_loop_t* loop, uv_fs_t* req, uv_dir_t* dir, uv_fs_cb cb);

    // Function @ uv.h:1422:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_readdir(uv_loop_t* loop, uv_fs_t* req, uv_dir_t* dir, uv_fs_cb cb);

    // Function @ uv.h:1418:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_opendir(uv_loop_t* loop, uv_fs_t* req, CString path, uv_fs_cb cb);

    // Function @ uv.h:1416:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_scandir_next(uv_fs_t* req, uv_dirent_t* ent);

    // Function @ uv.h:1411:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_scandir(uv_loop_t* loop, uv_fs_t* req, CString path, int flags, uv_fs_cb cb);

    // Function @ uv.h:1407:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_rmdir(uv_loop_t* loop, uv_fs_t* req, CString path, uv_fs_cb cb);

    // Function @ uv.h:1403:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_mkstemp(uv_loop_t* loop, uv_fs_t* req, CString tpl, uv_fs_cb cb);

    // Function @ uv.h:1399:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_mkdtemp(uv_loop_t* loop, uv_fs_t* req, CString tpl, uv_fs_cb cb);

    // Function @ uv.h:1394:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_mkdir(uv_loop_t* loop, uv_fs_t* req, CString path, int mode, uv_fs_cb cb);

    // Function @ uv.h:1388:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_copyfile(uv_loop_t* loop, uv_fs_t* req, CString path, CString new_path, int flags, uv_fs_cb cb);

    // Function @ uv.h:1363:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_write(uv_loop_t* loop, uv_fs_t* req, uv_file file, uv_buf_t* bufs, uint nbufs, long offset, uv_fs_cb cb);

    // Function @ uv.h:1359:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_unlink(uv_loop_t* loop, uv_fs_t* req, CString path, uv_fs_cb cb);

    // Function @ uv.h:1352:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_read(uv_loop_t* loop, uv_fs_t* req, uv_file file, uv_buf_t* bufs, uint nbufs, long offset, uv_fs_cb cb);

    // Function @ uv.h:1346:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_open(uv_loop_t* loop, uv_fs_t* req, CString path, int flags, int mode, uv_fs_cb cb);

    // Function @ uv.h:1342:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_close(uv_loop_t* loop, uv_fs_t* req, uv_file file, uv_fs_cb cb);

    // Function @ uv.h:1341:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_fs_req_cleanup(uv_fs_t* req);

    // Function @ uv.h:1339:22 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_stat_t* uv_fs_get_statbuf(uv_fs_t* param);

    // Function @ uv.h:1338:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString uv_fs_get_path(uv_fs_t* param);

    // Function @ uv.h:1337:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void* uv_fs_get_ptr(uv_fs_t* param);

    // Function @ uv.h:1336:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_get_system_error(uv_fs_t* param);

    // Function @ uv.h:1335:19 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fs_get_result(uv_fs_t* param);

    // Function @ uv.h:1334:22 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_fs_type uv_fs_get_type(uv_fs_t* param);

    // Function @ uv.h:1271:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern ulong uv_metrics_idle_time(uv_loop_t* loop);

    // Function @ uv.h:1269:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_uname(uv_utsname_t* buffer);

    // Function @ uv.h:1267:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_gethostname(CString buffer, uint* size);

    // Function @ uv.h:1254:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_unsetenv(CString name);

    // Function @ uv.h:1253:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_setenv(CString name, CString value);

    // Function @ uv.h:1252:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_getenv(CString name, CString buffer, uint* size);

    // Function @ uv.h:1251:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_os_free_environ(uv_env_item_t* envitems, int count);

    // Function @ uv.h:1250:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_environ(uv_env_item_t** envitems, int* count);

    // Function @ uv.h:1242:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_free_interface_addresses(uv_interface_address_t* addresses, int count);

    // Function @ uv.h:1240:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_interface_addresses(uv_interface_address_t** addresses, int* count);

    // Function @ uv.h:1238:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_free_cpu_info(uv_cpu_info_t* cpu_infos, int count);

    // Function @ uv.h:1237:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_cpu_info(uv_cpu_info_t** cpu_infos, int* count);

    // Function @ uv.h:1235:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_setpriority(uv_pid_t pid, int priority);

    // Function @ uv.h:1234:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_getpriority(uv_pid_t pid, int* priority);

    // Function @ uv.h:1215:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_pid_t uv_os_getppid();

    // Function @ uv.h:1214:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_pid_t uv_os_getpid();

    // Function @ uv.h:1213:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_os_free_passwd(uv_passwd_t* pwd);

    // Function @ uv.h:1212:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_get_passwd(uv_passwd_t* pwd);

    // Function @ uv.h:1211:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_tmpdir(CString buffer, uint* size);

    // Function @ uv.h:1210:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_os_homedir(CString buffer, uint* size);

    // Function @ uv.h:1208:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_getrusage(uv_rusage_t* rusage);

    // Function @ uv.h:1177:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_open_osfhandle(uv_os_fd_t os_fd);

    // Function @ uv.h:1176:22 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_os_fd_t uv_get_osfhandle(int fd);

    // Function @ uv.h:1175:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_uptime(double* uptime);

    // Function @ uv.h:1174:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_resident_set_memory(uint* rss);

    // Function @ uv.h:1173:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_set_process_title(CString title);

    // Function @ uv.h:1172:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_get_process_title(CString buffer, uint size);

    // Function @ uv.h:1171:18 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString* uv_setup_args(int argc, CString* argv);

    // Function @ uv.h:1095:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_cancel(uv_req_t* req);

    // Function @ uv.h:1090:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_queue_work(uv_loop_t* loop, uv_work_t* req, uv_work_cb work_cb, uv_after_work_cb after_work_cb);

    // Function @ uv.h:1076:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_pid_t uv_process_get_pid(uv_process_t* param);

    // Function @ uv.h:1075:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_kill(int pid, int signum);

    // Function @ uv.h:1074:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_process_kill(uv_process_t* param, int signum);

    // Function @ uv.h:1071:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_spawn(uv_loop_t* loop, uv_process_t* handle, uv_process_options_t* options);

    // Function @ uv.h:926:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_getnameinfo(uv_loop_t* loop, uv_getnameinfo_t* req, uv_getnameinfo_cb getnameinfo_cb, sockaddr* addr, int flags);

    // Function @ uv.h:910:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_freeaddrinfo(addrinfo* ai);

    // Function @ uv.h:904:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_getaddrinfo(uv_loop_t* loop, uv_getaddrinfo_t* req, uv_getaddrinfo_cb getaddrinfo_cb, CString node, CString service, addrinfo* hints);

    // Function @ uv.h:887:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern ulong uv_timer_get_due_in(uv_timer_t* handle);

    // Function @ uv.h:886:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern ulong uv_timer_get_repeat(uv_timer_t* handle);

    // Function @ uv.h:885:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_timer_set_repeat(uv_timer_t* handle, ulong repeat);

    // Function @ uv.h:884:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_timer_again(uv_timer_t* handle);

    // Function @ uv.h:883:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_timer_stop(uv_timer_t* handle);

    // Function @ uv.h:879:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_timer_start(uv_timer_t* handle, uv_timer_cb cb, ulong timeout, ulong repeat);

    // Function @ uv.h:878:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_timer_init(uv_loop_t* param, uv_timer_t* handle);

    // Function @ uv.h:865:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_async_send(uv_async_t* async);

    // Function @ uv.h:862:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_async_init(uv_loop_t* param, uv_async_t* async, uv_async_cb async_cb);

    // Function @ uv.h:854:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_idle_stop(uv_idle_t* idle);

    // Function @ uv.h:853:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_idle_start(uv_idle_t* idle, uv_idle_cb cb);

    // Function @ uv.h:852:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_idle_init(uv_loop_t* param, uv_idle_t* idle);

    // Function @ uv.h:844:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_check_stop(uv_check_t* check);

    // Function @ uv.h:843:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_check_start(uv_check_t* check, uv_check_cb cb);

    // Function @ uv.h:842:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_check_init(uv_loop_t* param, uv_check_t* check);

    // Function @ uv.h:834:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_prepare_stop(uv_prepare_t* prepare);

    // Function @ uv.h:833:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_prepare_start(uv_prepare_t* prepare, uv_prepare_cb cb);

    // Function @ uv.h:832:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_prepare_init(uv_loop_t* param, uv_prepare_t* prepare);

    // Function @ uv.h:824:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_poll_stop(uv_poll_t* handle);

    // Function @ uv.h:823:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_poll_start(uv_poll_t* handle, int events, uv_poll_cb cb);

    // Function @ uv.h:820:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_poll_init_socket(uv_loop_t* loop, uv_poll_t* handle, uv_os_sock_t socket);

    // Function @ uv.h:819:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_poll_init(uv_loop_t* loop, uv_poll_t* handle, int fd);

    // Function @ uv.h:803:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_pipe_chmod(uv_pipe_t* handle, int flags);

    // Function @ uv.h:802:26 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_handle_type uv_pipe_pending_type(uv_pipe_t* handle);

    // Function @ uv.h:801:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_pipe_pending_count(uv_pipe_t* handle);

    // Function @ uv.h:800:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_pipe_pending_instances(uv_pipe_t* handle, int count);

    // Function @ uv.h:797:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_pipe_getpeername(uv_pipe_t* handle, CString buffer, uint* size);

    // Function @ uv.h:794:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_pipe_getsockname(uv_pipe_t* handle, CString buffer, uint* size);

    // Function @ uv.h:790:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_pipe_connect(uv_connect_t* req, uv_pipe_t* handle, CString name, uv_connect_cb cb);

    // Function @ uv.h:789:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_pipe_bind(uv_pipe_t* handle, CString name);

    // Function @ uv.h:788:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_pipe_open(uv_pipe_t* param, uv_file file);

    // Function @ uv.h:787:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_pipe_init(uv_loop_t* param, uv_pipe_t* handle, int ipc);

    // Function @ uv.h:772:26 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_handle_type uv_guess_handle(uv_file file);

    // Function @ uv.h:760:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tty_get_vterm_state(uv_tty_vtermstate_t* state);

    // Function @ uv.h:759:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_tty_set_vterm_state(uv_tty_vtermstate_t state);

    // Function @ uv.h:758:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tty_get_winsize(uv_tty_t* param, int* width, int* height);

    // Function @ uv.h:757:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tty_reset_mode();

    // Function @ uv.h:756:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tty_set_mode(uv_tty_t* param, uv_tty_mode_t mode);

    // Function @ uv.h:755:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tty_init(uv_loop_t* param, uv_tty_t* param2, uv_file fd, int readable);

    // Function @ uv.h:719:18 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uint uv_udp_get_send_queue_count(uv_udp_t* handle);

    // Function @ uv.h:718:18 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uint uv_udp_get_send_queue_size(uv_udp_t* handle);

    // Function @ uv.h:717:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_recv_stop(uv_udp_t* handle);

    // Function @ uv.h:716:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_using_recvmmsg(uv_udp_t* handle);

    // Function @ uv.h:713:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_recv_start(uv_udp_t* handle, uv_alloc_cb alloc_cb, uv_udp_recv_cb recv_cb);

    // Function @ uv.h:709:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_try_send(uv_udp_t* handle, uv_buf_t* bufs, uint nbufs, sockaddr* addr);

    // Function @ uv.h:703:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_send(uv_udp_send_t* req, uv_udp_t* handle, uv_buf_t* bufs, uint nbufs, sockaddr* addr, uv_udp_send_cb send_cb);

    // Function @ uv.h:702:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_set_ttl(uv_udp_t* handle, int ttl);

    // Function @ uv.h:701:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_set_broadcast(uv_udp_t* handle, int on);

    // Function @ uv.h:699:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_set_multicast_interface(uv_udp_t* handle, CString interface_addr);

    // Function @ uv.h:698:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_set_multicast_ttl(uv_udp_t* handle, int ttl);

    // Function @ uv.h:697:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_set_multicast_loop(uv_udp_t* handle, int on);

    // Function @ uv.h:692:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_set_source_membership(uv_udp_t* handle, CString multicast_addr, CString interface_addr, CString source_addr, uv_membership membership);

    // Function @ uv.h:688:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_set_membership(uv_udp_t* handle, CString multicast_addr, CString interface_addr, uv_membership membership);

    // Function @ uv.h:685:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_getsockname(uv_udp_t* handle, sockaddr* name, int* namelen);

    // Function @ uv.h:682:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_getpeername(uv_udp_t* handle, sockaddr* name, int* namelen);

    // Function @ uv.h:680:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_connect(uv_udp_t* handle, sockaddr* addr);

    // Function @ uv.h:677:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_bind(uv_udp_t* handle, sockaddr* addr, uint flags);

    // Function @ uv.h:676:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_open(uv_udp_t* handle, uv_os_sock_t sock);

    // Function @ uv.h:675:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_init_ex(uv_loop_t* param, uv_udp_t* handle, uint flags);

    // Function @ uv.h:674:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_udp_init(uv_loop_t* param, uv_udp_t* handle);

    // Function @ uv.h:583:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_connect(uv_connect_t* req, uv_tcp_t* handle, sockaddr* addr, uv_connect_cb cb);

    // Function @ uv.h:582:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_close_reset(uv_tcp_t* handle, uv_close_cb close_cb);

    // Function @ uv.h:579:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_getpeername(uv_tcp_t* handle, sockaddr* name, int* namelen);

    // Function @ uv.h:576:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_getsockname(uv_tcp_t* handle, sockaddr* name, int* namelen);

    // Function @ uv.h:573:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_bind(uv_tcp_t* handle, sockaddr* addr, uint flags);

    // Function @ uv.h:566:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_simultaneous_accepts(uv_tcp_t* handle, int enable);

    // Function @ uv.h:563:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_keepalive(uv_tcp_t* handle, int enable, uint delay);

    // Function @ uv.h:562:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_nodelay(uv_tcp_t* handle, int enable);

    // Function @ uv.h:561:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_open(uv_tcp_t* handle, uv_os_sock_t sock);

    // Function @ uv.h:560:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_init_ex(uv_loop_t* param, uv_tcp_t* handle, uint flags);

    // Function @ uv.h:559:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_tcp_init(uv_loop_t* param, uv_tcp_t* handle);

    // Function @ uv.h:545:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_is_closing(uv_handle_t* handle);

    // Function @ uv.h:543:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_stream_set_blocking(uv_stream_t* handle, int blocking);

    // Function @ uv.h:541:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_is_writable(uv_stream_t* handle);

    // Function @ uv.h:540:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_is_readable(uv_stream_t* handle);

    // Function @ uv.h:526:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_try_write(uv_stream_t* handle, uv_buf_t* bufs, uint nbufs);

    // Function @ uv.h:520:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_write2(uv_write_t* req, uv_stream_t* handle, uv_buf_t* bufs, uint nbufs, uv_stream_t* send_handle, uv_write_cb cb);

    // Function @ uv.h:515:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_write(uv_write_t* req, uv_stream_t* handle, uv_buf_t* bufs, uint nbufs, uv_write_cb cb);

    // Function @ uv.h:513:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_read_stop(uv_stream_t* param);

    // Function @ uv.h:510:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_read_start(uv_stream_t* param, uv_alloc_cb alloc_cb, uv_read_cb read_cb);

    // Function @ uv.h:508:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_accept(uv_stream_t* server, uv_stream_t* client);

    // Function @ uv.h:507:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_listen(uv_stream_t* stream, int backlog, uv_connection_cb cb);

    // Function @ uv.h:505:18 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uint uv_stream_get_write_queue_size(uv_stream_t* stream);

    // Function @ uv.h:479:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_socketpair(int type, int protocol, uv_os_sock_t* socket_vector, int flags0, int flags1);

    // Function @ uv.h:478:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_pipe(uv_file* fds, int read_flags, int write_flags);

    // Function @ uv.h:476:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_buf_t uv_buf_init(CString @base, uint len);

    // Function @ uv.h:474:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_fileno(uv_handle_t* handle, uv_os_fd_t* fd);

    // Function @ uv.h:472:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_recv_buffer_size(uv_handle_t* handle, int* value);

    // Function @ uv.h:471:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_send_buffer_size(uv_handle_t* handle, int* value);

    // Function @ uv.h:469:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_close(uv_handle_t* handle, uv_close_cb close_cb);

    // Function @ uv.h:467:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_print_active_handles(uv_loop_t* loop, FILE* stream);

    // Function @ uv.h:466:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_print_all_handles(uv_loop_t* loop, FILE* stream);

    // Function @ uv.h:463:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_walk(uv_loop_t* loop, uv_walk_cb walk_cb, void* arg);

    // Function @ uv.h:461:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_is_active(uv_handle_t* handle);

    // Function @ uv.h:459:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString uv_req_type_name(uv_req_type type);

    // Function @ uv.h:458:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_req_type uv_req_get_type(uv_req_t* req);

    // Function @ uv.h:457:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_req_set_data(uv_req_t* req, void* data);

    // Function @ uv.h:456:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void* uv_req_get_data(uv_req_t* req);

    // Function @ uv.h:455:18 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uint uv_req_size(uv_req_type type);

    // Function @ uv.h:453:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_handle_set_data(uv_handle_t* handle, void* data);

    // Function @ uv.h:452:22 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_loop_t* uv_handle_get_loop(uv_handle_t* handle);

    // Function @ uv.h:451:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void* uv_handle_get_data(uv_handle_t* handle);

    // Function @ uv.h:450:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString uv_handle_type_name(uv_handle_type type);

    // Function @ uv.h:449:26 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_handle_type uv_handle_get_type(uv_handle_t* handle);

    // Function @ uv.h:448:18 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uint uv_handle_size(uv_handle_type type);

    // Function @ uv.h:416:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_shutdown(uv_shutdown_t* req, uv_stream_t* handle, uv_shutdown_cb cb);

    // Function @ uv.h:394:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString uv_err_name_r(int err, CString buf, uint buflen);

    // Function @ uv.h:393:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString uv_err_name(int err);

    // Function @ uv.h:391:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString uv_strerror_r(int err, CString buf, uint buflen);

    // Function @ uv.h:390:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString uv_strerror(int err);

    // Function @ uv.h:388:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_translate_sys_error(int sys_errno);

    // Function @ uv.h:307:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_backend_timeout(uv_loop_t* param);

    // Function @ uv.h:306:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_backend_fd(uv_loop_t* param);

    // Function @ uv.h:304:20 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern ulong uv_now(uv_loop_t* param);

    // Function @ uv.h:303:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_update_time(uv_loop_t* param);

    // Function @ uv.h:301:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_has_ref(uv_handle_t* param);

    // Function @ uv.h:300:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_unref(uv_handle_t* param);

    // Function @ uv.h:299:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_ref(uv_handle_t* param);

    // Function @ uv.h:297:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_stop(uv_loop_t* param);

    // Function @ uv.h:296:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_run(uv_loop_t* param, uv_run_mode mode);

    // Function @ uv.h:294:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_loop_fork(uv_loop_t* loop);

    // Function @ uv.h:293:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_loop_configure(uv_loop_t* loop, uv_loop_option option);

    // Function @ uv.h:292:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_loop_alive(uv_loop_t* loop);

    // Function @ uv.h:291:18 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uint uv_loop_size();

    // Function @ uv.h:290:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_loop_delete(uv_loop_t* param);

    // Function @ uv.h:284:22 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_loop_t* uv_loop_new();

    // Function @ uv.h:278:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_loop_close(uv_loop_t* loop);

    // Function @ uv.h:277:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_loop_init(uv_loop_t* loop);

    // Function @ uv.h:276:22 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uv_loop_t* uv_default_loop();

    // Function @ uv.h:271:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern int uv_replace_allocator(uv_malloc_func malloc_func, uv_realloc_func realloc_func, uv_calloc_func calloc_func, uv_free_func free_func);

    // Function @ uv.h:269:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern void uv_library_shutdown();

    // Function @ uv.h:262:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern CString uv_version_string();

    // Function @ uv.h:261:24 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [DllImport(LibraryName)]
    public static extern uint uv_version();

    // FunctionPointer @ _pthread_types.h:58:9 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/_pthread/_pthread_types.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_UV_VoidPtr_Void
    {
        public delegate* unmanaged<void*, void> Pointer;
    }

    // FunctionPointer @ uv.h:1759:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_thread_cb
    {
        public delegate* unmanaged<void*, void> Pointer;
    }

    // FunctionPointer @ uv.h:1750:49 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct FnPtr_UV_Void
    {
        public delegate* unmanaged<void> Pointer;
    }

    // FunctionPointer @ uv.h:338:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_random_cb
    {
        public delegate* unmanaged<uv_random_t*, int, void*, uint, void> Pointer;
    }

    // FunctionPointer @ uv.h:369:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_fs_event_cb
    {
        public delegate* unmanaged<uv_fs_event_t*, CString, int, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:379:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_signal_cb
    {
        public delegate* unmanaged<uv_signal_t*, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:374:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_fs_poll_cb
    {
        public delegate* unmanaged<uv_fs_poll_t*, int, uv_stat_t*, uv_stat_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:328:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_fs_cb
    {
        public delegate* unmanaged<uv_fs_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:330:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_after_work_cb
    {
        public delegate* unmanaged<uv_work_t*, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:329:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_work_cb
    {
        public delegate* unmanaged<uv_work_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:326:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_exit_cb
    {
        public delegate* unmanaged<uv_process_t*, long, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:334:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_getnameinfo_cb
    {
        public delegate* unmanaged<uv_getnameinfo_t*, int, CString, CString, void> Pointer;
    }

    // FunctionPointer @ uv.h:331:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_getaddrinfo_cb
    {
        public delegate* unmanaged<uv_getaddrinfo_t*, int, addrinfo*, void> Pointer;
    }

    // FunctionPointer @ uv.h:321:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_timer_cb
    {
        public delegate* unmanaged<uv_timer_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:322:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_async_cb
    {
        public delegate* unmanaged<uv_async_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:325:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_idle_cb
    {
        public delegate* unmanaged<uv_idle_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:324:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_check_cb
    {
        public delegate* unmanaged<uv_check_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:323:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_prepare_cb
    {
        public delegate* unmanaged<uv_prepare_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:320:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_poll_cb
    {
        public delegate* unmanaged<uv_poll_t*, int, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:316:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_connect_cb
    {
        public delegate* unmanaged<uv_connect_t*, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:644:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_udp_recv_cb
    {
        public delegate* unmanaged<uv_udp_t*, int, uv_buf_t*, sockaddr*, uint, void> Pointer;
    }

    // FunctionPointer @ uv.h:309:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_alloc_cb
    {
        public delegate* unmanaged<uv_handle_t*, uint, uv_buf_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:643:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_udp_send_cb
    {
        public delegate* unmanaged<uv_udp_send_t*, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:319:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_close_cb
    {
        public delegate* unmanaged<uv_handle_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:315:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_write_cb
    {
        public delegate* unmanaged<uv_write_t*, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:312:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_read_cb
    {
        public delegate* unmanaged<uv_stream_t*, int, uv_buf_t*, void> Pointer;
    }

    // FunctionPointer @ uv.h:318:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_connection_cb
    {
        public delegate* unmanaged<uv_stream_t*, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:327:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_walk_cb
    {
        public delegate* unmanaged<uv_handle_t*, void*, void> Pointer;
    }

    // FunctionPointer @ uv.h:317:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_shutdown_cb
    {
        public delegate* unmanaged<uv_shutdown_t*, int, void> Pointer;
    }

    // FunctionPointer @ uv.h:267:16 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_free_func
    {
        public delegate* unmanaged<void*, void> Pointer;
    }

    // FunctionPointer @ uv.h:266:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_calloc_func
    {
        public delegate* unmanaged<uint, uint, void*> Pointer;
    }

    // FunctionPointer @ uv.h:265:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_realloc_func
    {
        public delegate* unmanaged<void*, uint, void*> Pointer;
    }

    // FunctionPointer @ uv.h:264:17 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_malloc_func
    {
        public delegate* unmanaged<uint, void*> Pointer;
    }

    // Struct @ uv.h:1774:36 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct uv_thread_options_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uint flags;

        [FieldOffset(4)] // size = 4, padding = 0
        public uint stack_size;
    }

    // Struct @ uv.h:1187:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 12, Pack = 4)]
    public struct uv_timeval64_t
    {
        [FieldOffset(0)] // size = 8, padding = 0
        public long tv_sec;

        [FieldOffset(8)] // size = 4, padding = 0
        public int tv_usec;
    }

    // Struct @ uv.h:366:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 128, Pack = 4)]
    public struct uv_stat_t
    {
        [FieldOffset(0)] // size = 8, padding = 0
        public ulong st_dev;

        [FieldOffset(8)] // size = 8, padding = 0
        public ulong st_mode;

        [FieldOffset(16)] // size = 8, padding = 0
        public ulong st_nlink;

        [FieldOffset(24)] // size = 8, padding = 0
        public ulong st_uid;

        [FieldOffset(32)] // size = 8, padding = 0
        public ulong st_gid;

        [FieldOffset(40)] // size = 8, padding = 0
        public ulong st_rdev;

        [FieldOffset(48)] // size = 8, padding = 0
        public ulong st_ino;

        [FieldOffset(56)] // size = 8, padding = 0
        public ulong st_size;

        [FieldOffset(64)] // size = 8, padding = 0
        public ulong st_blksize;

        [FieldOffset(72)] // size = 8, padding = 0
        public ulong st_blocks;

        [FieldOffset(80)] // size = 8, padding = 0
        public ulong st_flags;

        [FieldOffset(88)] // size = 8, padding = 0
        public ulong st_gen;

        [FieldOffset(96)] // size = 8, padding = 0
        public uv_timespec_t st_atim;

        [FieldOffset(104)] // size = 8, padding = 0
        public uv_timespec_t st_mtim;

        [FieldOffset(112)] // size = 8, padding = 0
        public uv_timespec_t st_ctim;

        [FieldOffset(120)] // size = 8, padding = 0
        public uv_timespec_t st_birthtim;
    }

    // Struct @ uv.h:346:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct uv_timespec_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public int tv_sec;

        [FieldOffset(4)] // size = 4, padding = 0
        public int tv_nsec;
    }

    // Struct @ uv.h:244:28 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct uv_dirent_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public CString name;

        [FieldOffset(4)] // size = 4, padding = 0
        public uv_dirent_type_t type;
    }

    // Struct @ unix.h:126:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct uv_buf_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public CString @base;

        [FieldOffset(4)] // size = 4, padding = 0
        public uint len;
    }

    // Struct @ uv.h:246:29 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 1024, Pack = 1)]
    public struct uv_utsname_t
    {
        [FieldOffset(0)] // size = 256, padding = 0
        public fixed byte _sysname[256 / 1]; // char[256]

        public string sysname
        {
            get
            {
                fixed (uv_utsname_t* @this = &this)
                {
                    var pointer = &@this->_sysname[0];
                    var cString = new CString(pointer);
                    return Runtime.String(cString);
                }
            }
        }

        [FieldOffset(256)] // size = 256, padding = 0
        public fixed byte _release[256 / 1]; // char[256]

        public string release
        {
            get
            {
                fixed (uv_utsname_t* @this = &this)
                {
                    var pointer = &@this->_release[0];
                    var cString = new CString(pointer);
                    return Runtime.String(cString);
                }
            }
        }

        [FieldOffset(512)] // size = 256, padding = 0
        public fixed byte _version[256 / 1]; // char[256]

        public string version
        {
            get
            {
                fixed (uv_utsname_t* @this = &this)
                {
                    var pointer = &@this->_version[0];
                    var cString = new CString(pointer);
                    return Runtime.String(cString);
                }
            }
        }

        [FieldOffset(768)] // size = 256, padding = 0
        public fixed byte _machine[256 / 1]; // char[256]

        public string machine
        {
            get
            {
                fixed (uv_utsname_t* @this = &this)
                {
                    var pointer = &@this->_machine[0];
                    var cString = new CString(pointer);
                    return Runtime.String(cString);
                }
            }
        }
    }

    // Struct @ uv.h:241:30 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct uv_env_item_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public CString name;

        [FieldOffset(4)] // size = 4, padding = 0
        public CString value;
    }

    // Struct @ uv.h:243:39 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 72, Pack = 4)]
    public struct uv_interface_address_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public CString name;

        [FieldOffset(4)] // size = 6, padding = 2
        public fixed byte _phys_addr[6 / 1]; // char[6]

        public string phys_addr
        {
            get
            {
                fixed (uv_interface_address_t* @this = &this)
                {
                    var pointer = &@this->_phys_addr[0];
                    var cString = new CString(pointer);
                    return Runtime.String(cString);
                }
            }
        }

        [FieldOffset(12)] // size = 4, padding = 0
        public int is_internal;

        [FieldOffset(16)] // size = 28, padding = 0
        public uv_interface_address_t_address address;

        [FieldOffset(44)] // size = 28, padding = 0
        public uv_interface_address_t_netmask netmask;

        // Union @ uv.h:1116:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
        [StructLayout(LayoutKind.Explicit, Size = 28, Pack = 4)]
        public struct uv_interface_address_t_address
        {
            [FieldOffset(0)] // size = 16, padding = 0
            public sockaddr_in address4;

            [FieldOffset(0)] // size = 28, padding = 0
            public sockaddr_in6 address6;
        }

        // Union @ uv.h:1120:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
        [StructLayout(LayoutKind.Explicit, Size = 28, Pack = 4)]
        public struct uv_interface_address_t_netmask
        {
            [FieldOffset(0)] // size = 16, padding = 0
            public sockaddr_in netmask4;

            [FieldOffset(0)] // size = 28, padding = 0
            public sockaddr_in6 netmask6;
        }
    }

    // Struct @ uv.h:242:30 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 48, Pack = 4)]
    public struct uv_cpu_info_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public CString model;

        [FieldOffset(4)] // size = 4, padding = 0
        public int speed;

        [FieldOffset(8)] // size = 40, padding = 0
        public uv_cpu_times_s cpu_times;
    }

    // Struct @ uv.h:1098:8 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 40, Pack = 4)]
    public struct uv_cpu_times_s
    {
        [FieldOffset(0)] // size = 8, padding = 0
        public ulong user;

        [FieldOffset(8)] // size = 8, padding = 0
        public ulong nice;

        [FieldOffset(16)] // size = 8, padding = 0
        public ulong sys;

        [FieldOffset(24)] // size = 8, padding = 0
        public ulong idle;

        [FieldOffset(32)] // size = 8, padding = 0
        public ulong irq;
    }

    // Struct @ uv.h:245:28 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 20, Pack = 4)]
    public struct uv_passwd_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public CString username;

        [FieldOffset(4)] // size = 4, padding = 0
        public int uid;

        [FieldOffset(8)] // size = 4, padding = 0
        public int gid;

        [FieldOffset(12)] // size = 4, padding = 0
        public CString shell;

        [FieldOffset(16)] // size = 4, padding = 0
        public CString homedir;
    }

    // Struct @ uv.h:1206:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 128, Pack = 4)]
    public struct uv_rusage_t
    {
        [FieldOffset(0)] // size = 8, padding = 0
        public uv_timeval_t ru_utime;

        [FieldOffset(8)] // size = 8, padding = 0
        public uv_timeval_t ru_stime;

        [FieldOffset(16)] // size = 8, padding = 0
        public ulong ru_maxrss;

        [FieldOffset(24)] // size = 8, padding = 0
        public ulong ru_ixrss;

        [FieldOffset(32)] // size = 8, padding = 0
        public ulong ru_idrss;

        [FieldOffset(40)] // size = 8, padding = 0
        public ulong ru_isrss;

        [FieldOffset(48)] // size = 8, padding = 0
        public ulong ru_minflt;

        [FieldOffset(56)] // size = 8, padding = 0
        public ulong ru_majflt;

        [FieldOffset(64)] // size = 8, padding = 0
        public ulong ru_nswap;

        [FieldOffset(72)] // size = 8, padding = 0
        public ulong ru_inblock;

        [FieldOffset(80)] // size = 8, padding = 0
        public ulong ru_oublock;

        [FieldOffset(88)] // size = 8, padding = 0
        public ulong ru_msgsnd;

        [FieldOffset(96)] // size = 8, padding = 0
        public ulong ru_msgrcv;

        [FieldOffset(104)] // size = 8, padding = 0
        public ulong ru_nsignals;

        [FieldOffset(112)] // size = 8, padding = 0
        public ulong ru_nvcsw;

        [FieldOffset(120)] // size = 8, padding = 0
        public ulong ru_nivcsw;
    }

    // Struct @ uv.h:1182:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct uv_timeval_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public int tv_sec;

        [FieldOffset(4)] // size = 4, padding = 0
        public int tv_usec;
    }

    // Struct @ uv.h:1010:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 40, Pack = 4)]
    public struct uv_process_options_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uv_exit_cb exit_cb;

        [FieldOffset(4)] // size = 4, padding = 0
        public CString file;

        [FieldOffset(8)] // size = 4, padding = 0
        public CString* args;

        [FieldOffset(12)] // size = 4, padding = 0
        public CString* env;

        [FieldOffset(16)] // size = 4, padding = 0
        public CString cwd;

        [FieldOffset(20)] // size = 4, padding = 0
        public uint flags;

        [FieldOffset(24)] // size = 4, padding = 0
        public int stdio_count;

        [FieldOffset(28)] // size = 4, padding = 0
        public uv_stdio_container_t* stdio;

        [FieldOffset(32)] // size = 4, padding = 0
        public uv_uid_t uid;

        [FieldOffset(36)] // size = 4, padding = 0
        public uv_gid_t gid;
    }

    // Struct @ uv.h:965:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct uv_stdio_container_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uv_stdio_flags flags;

        [FieldOffset(4)] // size = 4, padding = 0
        public uv_stdio_container_t_data data;

        // Union @ uv.h:961:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
        [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
        public struct uv_stdio_container_t_data
        {
            [FieldOffset(0)] // size = 4, padding = 0
            public uv_stream_t* stream;

            [FieldOffset(0)] // size = 4, padding = 0
            public int fd;
        }
    }

    // Struct @ netdb.h:147:8 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/netdb.h)
    [StructLayout(LayoutKind.Explicit, Size = 32, Pack = 4)]
    public struct addrinfo
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public int ai_flags;

        [FieldOffset(4)] // size = 4, padding = 0
        public int ai_family;

        [FieldOffset(8)] // size = 4, padding = 0
        public int ai_socktype;

        [FieldOffset(12)] // size = 4, padding = 0
        public int ai_protocol;

        [FieldOffset(16)] // size = 4, padding = 0
        public socklen_t ai_addrlen;

        [FieldOffset(20)] // size = 4, padding = 0
        public CString ai_canonname;

        [FieldOffset(24)] // size = 4, padding = 0
        public sockaddr* ai_addr;

        [FieldOffset(28)] // size = 4, padding = 0
        public addrinfo* ai_next;
    }

    // OpaqueType @ uv.h:209:26 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_loop_t
    {
    }

    // OpaqueType @ unix.h:141:23 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_key_t
    {
    }

    // OpaqueType @ unix.h:135:24 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_once_t
    {
    }

    // OpaqueType @ unix.h:137:25 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_mutex_t
    {
    }

    // OpaqueType @ unix.h:140:24 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_cond_t
    {
    }

    // OpaqueType @ unix.h:162:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_barrier_t
    {
    }

    // OpaqueType @ unix.h:139:27 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_sem_t
    {
    }

    // OpaqueType @ unix.h:138:26 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_rwlock_t
    {
    }

    // OpaqueType @ unix.h:221:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_lib_t
    {
    }

    // OpaqueType @ uv.h:238:28 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_random_t
    {
    }

    // OpaqueType @ in6.h:170:8 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/netinet6/in6.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct sockaddr_in6
    {
    }

    // OpaqueType @ in.h:375:8 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/netinet/in.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct sockaddr_in
    {
    }

    // OpaqueType @ uv.h:224:30 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_fs_event_t
    {
    }

    // OpaqueType @ uv.h:226:28 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_signal_t
    {
    }

    // OpaqueType @ uv.h:225:29 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_fs_poll_t
    {
    }

    // OpaqueType @ uv.h:236:24 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_fs_t
    {
    }

    // OpaqueType @ uv.h:211:25 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_dir_t
    {
    }

    // OpaqueType @ uv.h:229:25 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_req_t
    {
    }

    // OpaqueType @ uv.h:237:26 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_work_t
    {
    }

    // OpaqueType @ uv.h:223:29 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_process_t
    {
    }

    // OpaqueType @ uv.h:212:28 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_stream_t
    {
    }

    // OpaqueType @ socket.h:408:8 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/socket.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct sockaddr
    {
    }

    // OpaqueType @ uv.h:231:33 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_getnameinfo_t
    {
    }

    // OpaqueType @ uv.h:230:33 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_getaddrinfo_t
    {
    }

    // OpaqueType @ uv.h:218:27 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_timer_t
    {
    }

    // OpaqueType @ uv.h:222:27 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_async_t
    {
    }

    // OpaqueType @ uv.h:221:26 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_idle_t
    {
    }

    // OpaqueType @ uv.h:220:27 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_check_t
    {
    }

    // OpaqueType @ uv.h:219:29 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_prepare_t
    {
    }

    // OpaqueType @ uv.h:217:26 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_poll_t
    {
    }

    // OpaqueType @ uv.h:215:26 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_pipe_t
    {
    }

    // OpaqueType @ uv.h:234:29 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_connect_t
    {
    }

    // OpaqueType @ uv.h:216:25 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_tty_t
    {
    }

    // OpaqueType @ uv.h:214:25 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_udp_t
    {
    }

    // OpaqueType @ uv.h:210:28 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_handle_t
    {
    }

    // OpaqueType @ uv.h:235:30 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_udp_send_t
    {
    }

    // OpaqueType @ uv.h:213:25 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_tcp_t
    {
    }

    // OpaqueType @ uv.h:233:27 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_write_t
    {
    }

    // OpaqueType @ uv.h:232:30 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    [StructLayout(LayoutKind.Sequential)]
    public struct uv_shutdown_t
    {
    }

    // Typedef @ unix.h:136:19 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct uv_thread_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public pthread_t Data;

        public static implicit operator pthread_t(uv_thread_t data) => data.Data;
        public static implicit operator uv_thread_t(pthread_t data) => new() { Data = data };
    }

    // Typedef @ _pthread_t.h:31:28 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/_pthread/_pthread_t.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct pthread_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public IntPtr Data;

        public static implicit operator IntPtr(pthread_t data) => data.Data;
        public static implicit operator pthread_t(IntPtr data) => new() { Data = data };
    }

    // Typedef @ unix.h:168:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct uv_gid_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public gid_t Data;

        public static implicit operator gid_t(uv_gid_t data) => data.Data;
        public static implicit operator uv_gid_t(gid_t data) => new() { Data = data };
    }

    // Typedef @ _gid_t.h:31:25 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/_types/_gid_t.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct gid_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uint Data;

        public static implicit operator uint(gid_t data) => data.Data;
        public static implicit operator gid_t(uint data) => new() { Data = data };
    }

    // Typedef @ unix.h:169:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct uv_uid_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uid_t Data;

        public static implicit operator uid_t(uv_uid_t data) => data.Data;
        public static implicit operator uv_uid_t(uid_t data) => new() { Data = data };
    }

    // Typedef @ _uid_t.h:31:31 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/_types/_uid_t.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct uid_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uint Data;

        public static implicit operator uint(uid_t data) => data.Data;
        public static implicit operator uid_t(uint data) => new() { Data = data };
    }

    // Typedef @ unix.h:128:13 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct uv_file
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public int Data;

        public static implicit operator int(uv_file data) => data.Data;
        public static implicit operator uv_file(int data) => new() { Data = data };
    }

    // Typedef @ unix.h:131:15 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct uv_pid_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public pid_t Data;

        public static implicit operator pid_t(uv_pid_t data) => data.Data;
        public static implicit operator uv_pid_t(pid_t data) => new() { Data = data };
    }

    // Typedef @ _pid_t.h:31:31 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/_types/_pid_t.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct pid_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public int Data;

        public static implicit operator int(pid_t data) => data.Data;
        public static implicit operator pid_t(int data) => new() { Data = data };
    }

    // Typedef @ unix.h:130:13 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct uv_os_fd_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public int Data;

        public static implicit operator int(uv_os_fd_t data) => data.Data;
        public static implicit operator uv_os_fd_t(int data) => new() { Data = data };
    }

    // Typedef @ _socklen_t.h:31:33 (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/_types/_socklen_t.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct socklen_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public uint Data;

        public static implicit operator uint(socklen_t data) => data.Data;
        public static implicit operator socklen_t(uint data) => new() { Data = data };
    }

    // Typedef @ unix.h:129:13 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv/unix.h)
    [StructLayout(LayoutKind.Explicit, Size = 4, Pack = 4)]
    public struct uv_os_sock_t
    {
        [FieldOffset(0)] // size = 4, padding = 0
        public int Data;

        public static implicit operator int(uv_os_sock_t data) => data.Data;
        public static implicit operator uv_os_sock_t(int data) => new() { Data = data };
    }

    // Enum @ uv.h:1164:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_dirent_type_t : uint
    {
        UV_DIRENT_UNKNOWN = 0U,
        UV_DIRENT_FILE = 1U,
        UV_DIRENT_DIR = 2U,
        UV_DIRENT_LINK = 3U,
        UV_DIRENT_FIFO = 4U,
        UV_DIRENT_SOCKET = 5U,
        UV_DIRENT_CHAR = 6U,
        UV_DIRENT_BLOCK = 7U
    }

    // Enum @ uv.h:1312:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_fs_type : uint
    {
        UV_FS_UNKNOWN = 4294967295U,
        UV_FS_CUSTOM = 0U,
        UV_FS_OPEN = 1U,
        UV_FS_CLOSE = 2U,
        UV_FS_READ = 3U,
        UV_FS_WRITE = 4U,
        UV_FS_SENDFILE = 5U,
        UV_FS_STAT = 6U,
        UV_FS_LSTAT = 7U,
        UV_FS_FSTAT = 8U,
        UV_FS_FTRUNCATE = 9U,
        UV_FS_UTIME = 10U,
        UV_FS_FUTIME = 11U,
        UV_FS_ACCESS = 12U,
        UV_FS_CHMOD = 13U,
        UV_FS_FCHMOD = 14U,
        UV_FS_FSYNC = 15U,
        UV_FS_FDATASYNC = 16U,
        UV_FS_UNLINK = 17U,
        UV_FS_RMDIR = 18U,
        UV_FS_MKDIR = 19U,
        UV_FS_MKDTEMP = 20U,
        UV_FS_RENAME = 21U,
        UV_FS_SCANDIR = 22U,
        UV_FS_LINK = 23U,
        UV_FS_SYMLINK = 24U,
        UV_FS_READLINK = 25U,
        UV_FS_CHOWN = 26U,
        UV_FS_FCHOWN = 27U,
        UV_FS_REALPATH = 28U,
        UV_FS_COPYFILE = 29U,
        UV_FS_LCHOWN = 30U,
        UV_FS_OPENDIR = 31U,
        UV_FS_READDIR = 32U,
        UV_FS_CLOSEDIR = 33U,
        UV_FS_STATFS = 34U,
        UV_FS_MKSTEMP = 35U,
        UV_FS_LUTIME = 36U
    }

    // Enum @ uv.h:956:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_stdio_flags : uint
    {
        UV_IGNORE = 0U,
        UV_CREATE_PIPE = 1U,
        UV_INHERIT_FD = 2U,
        UV_INHERIT_STREAM = 4U,
        UV_READABLE_PIPE = 16U,
        UV_WRITABLE_PIPE = 32U,
        UV_NONBLOCK_PIPE = 64U,
        UV_OVERLAPPED_PIPE = 64U
    }

    // Enum @ uv.h:196:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_handle_type : uint
    {
        UV_UNKNOWN_HANDLE = 0U,
        UV_ASYNC = 1U,
        UV_CHECK = 2U,
        UV_FS_EVENT = 3U,
        UV_FS_POLL = 4U,
        UV_HANDLE = 5U,
        UV_IDLE = 6U,
        UV_NAMED_PIPE = 7U,
        UV_POLL = 8U,
        UV_PREPARE = 9U,
        UV_PROCESS = 10U,
        UV_STREAM = 11U,
        UV_TCP = 12U,
        UV_TIMER = 13U,
        UV_TTY = 14U,
        UV_UDP = 15U,
        UV_SIGNAL = 16U,
        UV_FILE = 17U,
        UV_HANDLE_TYPE_MAX = 18U
    }

    // Enum @ uv.h:752:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_tty_vtermstate_t : uint
    {
        UV_TTY_SUPPORTED = 0U,
        UV_TTY_UNSUPPORTED = 1U
    }

    // Enum @ uv.h:740:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_tty_mode_t : uint
    {
        UV_TTY_MODE_NORMAL = 0U,
        UV_TTY_MODE_RAW = 1U,
        UV_TTY_MODE_IO = 2U
    }

    // Enum @ uv.h:385:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_membership : uint
    {
        UV_LEAVE_GROUP = 0U,
        UV_JOIN_GROUP = 1U
    }

    // Enum @ uv.h:205:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_req_type : uint
    {
        UV_UNKNOWN_REQ = 0U,
        UV_REQ = 1U,
        UV_CONNECT = 2U,
        UV_WRITE = 3U,
        UV_SHUTDOWN = 4U,
        UV_UDP_SEND = 5U,
        UV_FS = 6U,
        UV_WORK = 7U,
        UV_GETADDRINFO = 8U,
        UV_GETNAMEINFO = 9U,
        UV_RANDOM = 10U,
        UV_REQ_TYPE_MAX = 11U
    }

    // Enum @ uv.h:258:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_run_mode : uint
    {
        UV_RUN_DEFAULT = 0U,
        UV_RUN_ONCE = 1U,
        UV_RUN_NOWAIT = 2U
    }

    // Enum @ uv.h:252:3 (/Users/lstranks/Programming/c2cs/ext/libuv/include/uv.h)
    public enum uv_loop_option : uint
    {
        UV_LOOP_BLOCK_SIGNAL = 0U,
        UV_METRICS_IDLE_TIME = 1U
    }
}
