// HintName: test_class.g.cs
// <auto-generated>
//  This code was generated by the following tool on DateTimeOffset_1:
//      https://github.com/bottlenoselabs/c2cs (Version)
//
//  Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ReSharper disable All

#region Template

#pragma warning disable CS1591
#pragma warning disable CS8981
using Interop.Runtime;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

#endregion

namespace test_namespace
{

    public static unsafe partial class test_class
    {
        private const string LibraryName = "test_class";

        public enum enum_uint8 : int
        {
            ENUM_UINT8_MIN = 0,
            ENUM_UINT8_MAX = 255
        }
    }

}
