//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the following tool:
//        https://github.com/lithiumtoast/c2cs
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

public static unsafe partial class test
{
    private const string LibraryName = "test";

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_time_t dds_time();

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_sleepfor(dds_duration_t reltime);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern ddsrt_wctime_t ddsrt_time_wallclock();

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern ddsrt_mtime_t ddsrt_time_monotonic();

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern ddsrt_etime_t ddsrt_time_elapsed();

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern ulong ddsrt_ctime(dds_time_t abstime, sbyte* str, ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_time_t ddsrt_time_add_duration(dds_time_t abstime, dds_duration_t reltime);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern ddsrt_mtime_t ddsrt_mtime_add_duration(ddsrt_mtime_t abstime, dds_duration_t reltime);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern ddsrt_wctime_t ddsrt_wctime_add_duration(ddsrt_wctime_t abstime, dds_duration_t reltime);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern ddsrt_etime_t ddsrt_etime_add_duration(ddsrt_etime_t abstime, dds_duration_t reltime);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void ddsrt_mtime_to_sec_usec(int* sec, int* usec, ddsrt_mtime_t t);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void ddsrt_wctime_to_sec_usec(int* sec, int* usec, ddsrt_wctime_t t);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void ddsrt_etime_to_sec_usec(int* sec, int* usec, ddsrt_etime_t t);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte* dds_strretcode(dds_return_t ret);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern uint dds_get_log_mask();

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_set_log_mask(uint cats);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_set_log_file(__sFILE* file);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_set_trace_file(__sFILE* file);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_set_log_sink(dds_log_write_fn_t callback, void* userdata);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_set_trace_sink(dds_log_write_fn_t callback, void* userdata);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_log_cfg_init(ddsrt_log_cfg* cfg, uint domid, uint tracemask, __sFILE* log_fp, __sFILE* trace_fp);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_log_cfg(ddsrt_log_cfg* cfg, uint prio, sbyte* file, uint line, sbyte* func, sbyte* fmt);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_log_id(uint prio, uint domid, sbyte* file, uint line, sbyte* func, sbyte* fmt);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_log(uint prio, sbyte* file, uint line, sbyte* func, sbyte* fmt);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void* dds_alloc(ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void* dds_realloc(void* ptr, ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void* dds_realloc_zero(void* ptr, ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_free(void* ptr);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte* dds_string_alloc(ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte* dds_string_dup(sbyte* str);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_string_free(sbyte* str);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_sample_free(void* sample, dds_topic_descriptor* desc, dds_free_op_t op);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_write_set_batch(CBool enable);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_qos_t* dds_create_qos();

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_qos_t* dds_qos_create();

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_delete_qos(dds_qos_t* qos);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qos_delete(dds_qos_t* qos);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_reset_qos(dds_qos_t* qos);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qos_reset(dds_qos_t* qos);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_copy_qos(dds_qos_t* dst, dds_qos_t* src);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_qos_copy(dds_qos_t* dst, dds_qos_t* src);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_merge_qos(dds_qos_t* dst, dds_qos_t* src);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qos_merge(dds_qos_t* dst, dds_qos_t* src);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qos_equal(dds_qos_t* a, dds_qos_t* b);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_userdata(dds_qos_t* qos, void* value, ulong sz);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_topicdata(dds_qos_t* qos, void* value, ulong sz);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_groupdata(dds_qos_t* qos, void* value, ulong sz);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_durability(dds_qos_t* qos, dds_durability_kind_t kind);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_history(dds_qos_t* qos, dds_history_kind_t kind, int depth);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_resource_limits(dds_qos_t* qos, int max_samples, int max_instances, int max_samples_per_instance);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_presentation(dds_qos_t* qos, dds_presentation_access_scope_kind_t access_scope, CBool coherent_access, CBool ordered_access);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_lifespan(dds_qos_t* qos, dds_duration_t lifespan);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_deadline(dds_qos_t* qos, dds_duration_t deadline);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_latency_budget(dds_qos_t* qos, dds_duration_t duration);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_ownership(dds_qos_t* qos, dds_ownership_kind_t kind);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_ownership_strength(dds_qos_t* qos, int value);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_liveliness(dds_qos_t* qos, dds_liveliness_kind_t kind, dds_duration_t lease_duration);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_time_based_filter(dds_qos_t* qos, dds_duration_t minimum_separation);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_partition(dds_qos_t* qos, uint n, sbyte* * ps);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_partition1(dds_qos_t* qos, sbyte* name);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_reliability(dds_qos_t* qos, dds_reliability_kind_t kind, dds_duration_t max_blocking_time);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_transport_priority(dds_qos_t* qos, int value);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_destination_order(dds_qos_t* qos, dds_destination_order_kind_t kind);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_writer_data_lifecycle(dds_qos_t* qos, CBool autodispose);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_reader_data_lifecycle(dds_qos_t* qos, dds_duration_t autopurge_nowriter_samples_delay, dds_duration_t autopurge_disposed_samples_delay);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_durability_service(dds_qos_t* qos, dds_duration_t service_cleanup_delay, dds_history_kind_t history_kind, int history_depth, int max_samples, int max_instances, int max_samples_per_instance);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_ignorelocal(dds_qos_t* qos, dds_ignorelocal_kind_t ignore);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_prop(dds_qos_t* qos, sbyte* name, sbyte* value);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qunset_prop(dds_qos_t* qos, sbyte* name);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_bprop(dds_qos_t* qos, sbyte* name, void* value, [In] ulong sz);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qunset_bprop(dds_qos_t* qos, sbyte* name);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_qset_type_consistency(dds_qos_t* qos, dds_type_consistency_kind_t kind, CBool ignore_sequence_bounds, CBool ignore_string_bounds, CBool ignore_member_names, CBool prevent_type_widening, CBool force_type_validation);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_userdata(dds_qos_t* qos, void* * value, ulong* sz);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_topicdata(dds_qos_t* qos, void* * value, ulong* sz);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_groupdata(dds_qos_t* qos, void* * value, ulong* sz);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_durability(dds_qos_t* qos, dds_durability_kind_t* kind);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_history(dds_qos_t* qos, dds_history_kind_t* kind, int* depth);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_resource_limits(dds_qos_t* qos, int* max_samples, int* max_instances, int* max_samples_per_instance);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_presentation(dds_qos_t* qos, dds_presentation_access_scope_kind_t* access_scope, CBool* coherent_access, CBool* ordered_access);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_lifespan(dds_qos_t* qos, dds_duration_t* lifespan);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_deadline(dds_qos_t* qos, dds_duration_t* deadline);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_latency_budget(dds_qos_t* qos, dds_duration_t* duration);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_ownership(dds_qos_t* qos, dds_ownership_kind_t* kind);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_ownership_strength(dds_qos_t* qos, int* value);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_liveliness(dds_qos_t* qos, dds_liveliness_kind_t* kind, dds_duration_t* lease_duration);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_time_based_filter(dds_qos_t* qos, dds_duration_t* minimum_separation);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_partition(dds_qos_t* qos, uint* n, sbyte* * * ps);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_reliability(dds_qos_t* qos, dds_reliability_kind_t* kind, dds_duration_t* max_blocking_time);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_transport_priority(dds_qos_t* qos, int* value);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_destination_order(dds_qos_t* qos, dds_destination_order_kind_t* kind);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_writer_data_lifecycle(dds_qos_t* qos, CBool* autodispose);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_reader_data_lifecycle(dds_qos_t* qos, dds_duration_t* autopurge_nowriter_samples_delay, dds_duration_t* autopurge_disposed_samples_delay);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_durability_service(dds_qos_t* qos, dds_duration_t* service_cleanup_delay, dds_history_kind_t* history_kind, int* history_depth, int* max_samples, int* max_instances, int* max_samples_per_instance);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_ignorelocal(dds_qos_t* qos, dds_ignorelocal_kind_t* ignore);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_propnames(dds_qos_t* qos, uint* n, sbyte* * * names);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_prop(dds_qos_t* qos, sbyte* name, sbyte* * value);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_bpropnames(dds_qos_t* qos, uint* n, sbyte* * * names);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_bprop(dds_qos_t* qos, sbyte* name, void* * value, ulong* sz);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern CBool dds_qget_type_consistency(dds_qos_t* qos, dds_type_consistency_kind_t* kind, CBool* ignore_sequence_bounds, CBool* ignore_string_bounds, CBool* ignore_member_names, CBool* prevent_type_widening, CBool* force_type_validation);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_inconsistent_topic_status(dds_entity_t topic, dds_inconsistent_topic_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_publication_matched_status(dds_entity_t writer, dds_publication_matched_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_liveliness_lost_status(dds_entity_t writer, dds_liveliness_lost_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_offered_deadline_missed_status(dds_entity_t writer, dds_offered_deadline_missed_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_offered_incompatible_qos_status(dds_entity_t writer, dds_offered_incompatible_qos_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_subscription_matched_status(dds_entity_t reader, dds_subscription_matched_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_liveliness_changed_status(dds_entity_t reader, dds_liveliness_changed_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_sample_rejected_status(dds_entity_t reader, dds_sample_rejected_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_sample_lost_status(dds_entity_t reader, dds_sample_lost_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_requested_deadline_missed_status(dds_entity_t reader, dds_requested_deadline_missed_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_requested_incompatible_qos_status(dds_entity_t reader, dds_requested_incompatible_qos_status_t* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_listener_t* dds_create_listener(void* arg);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_listener_t* dds_listener_create(void* arg);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_delete_listener(dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_listener_delete(dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_reset_listener(dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_listener_reset(dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_copy_listener(dds_listener_t* dst, dds_listener_t* src);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_listener_copy(dds_listener_t* dst, dds_listener_t* src);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_merge_listener(dds_listener_t* dst, dds_listener_t* src);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_listener_merge(dds_listener_t* dst, dds_listener_t* src);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_inconsistent_topic(dds_listener_t* listener, dds_on_inconsistent_topic_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_liveliness_lost(dds_listener_t* listener, dds_on_liveliness_lost_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_offered_deadline_missed(dds_listener_t* listener, dds_on_offered_deadline_missed_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_offered_incompatible_qos(dds_listener_t* listener, dds_on_offered_incompatible_qos_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_data_on_readers(dds_listener_t* listener, dds_on_data_on_readers_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_sample_lost(dds_listener_t* listener, dds_on_sample_lost_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_data_available(dds_listener_t* listener, dds_on_data_available_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_sample_rejected(dds_listener_t* listener, dds_on_sample_rejected_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_liveliness_changed(dds_listener_t* listener, dds_on_liveliness_changed_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_requested_deadline_missed(dds_listener_t* listener, dds_on_requested_deadline_missed_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_requested_incompatible_qos(dds_listener_t* listener, dds_on_requested_incompatible_qos_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_publication_matched(dds_listener_t* listener, dds_on_publication_matched_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lset_subscription_matched(dds_listener_t* listener, dds_on_subscription_matched_fn callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_inconsistent_topic(dds_listener_t* listener, dds_on_inconsistent_topic_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_liveliness_lost(dds_listener_t* listener, dds_on_liveliness_lost_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_offered_deadline_missed(dds_listener_t* listener, dds_on_offered_deadline_missed_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_offered_incompatible_qos(dds_listener_t* listener, dds_on_offered_incompatible_qos_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_data_on_readers(dds_listener_t* listener, dds_on_data_on_readers_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_sample_lost(dds_listener_t* listener, dds_on_sample_lost_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_data_available(dds_listener_t* listener, dds_on_data_available_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_sample_rejected(dds_listener_t* listener, dds_on_sample_rejected_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_liveliness_changed(dds_listener_t* listener, dds_on_liveliness_changed_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_requested_deadline_missed(dds_listener_t* listener, dds_on_requested_deadline_missed_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_requested_incompatible_qos(dds_listener_t* listener, dds_on_requested_incompatible_qos_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_publication_matched(dds_listener_t* listener, dds_on_publication_matched_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_lget_subscription_matched(dds_listener_t* listener, dds_on_subscription_matched_fn* callback);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_enable(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_delete(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_get_publisher(dds_entity_t writer);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_get_subscriber(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_get_datareader(dds_entity_t condition);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_mask(dds_entity_t condition, uint* mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_instance_handle(dds_entity_t entity, dds_instance_handle_t* ihdl);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_guid(dds_entity_t entity, dds_guid_t* guid);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_status(dds_entity_t entity, uint* status, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_status(dds_entity_t entity, uint* status, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_status_changes(dds_entity_t entity, uint* status);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_status_mask(dds_entity_t entity, uint* mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_enabled_status(dds_entity_t entity, uint* mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_set_status_mask(dds_entity_t entity, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_set_enabled_status(dds_entity_t entity, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_qos(dds_entity_t entity, dds_qos_t* qos);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_set_qos(dds_entity_t entity, dds_qos_t* qos);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_listener(dds_entity_t entity, dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_set_listener(dds_entity_t entity, dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_participant([In] dds_domainid_t domain, dds_qos_t* qos, dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_domain([In] dds_domainid_t domain, sbyte* config);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_domain_with_rawconfig([In] dds_domainid_t domain, ddsi_config* config);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_get_parent(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_get_participant(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_children(dds_entity_t entity, dds_entity_t* children, ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_domainid(dds_entity_t entity, dds_domainid_t* id);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_lookup_participant(dds_domainid_t domain_id, dds_entity_t* participants, ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_topic(dds_entity_t participant, dds_topic_descriptor_t* descriptor, sbyte* name, dds_qos_t* qos, dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_topic_sertype(dds_entity_t participant, sbyte* name, ddsi_sertype* * sertype, dds_qos_t* qos, dds_listener_t* listener, ddsi_plist* sedp_plist);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_topic_generic(dds_entity_t participant, ddsi_sertopic* * sertopic, dds_qos_t* qos, dds_listener_t* listener, ddsi_plist* sedp_plist);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_topic_arbitrary(dds_entity_t participant, ddsi_sertopic* sertopic, dds_qos_t* qos, dds_listener_t* listener, ddsi_plist* sedp_plist);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_find_topic(dds_entity_t participant, sbyte* name);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_name(dds_entity_t topic, sbyte* name, ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_type_name(dds_entity_t topic, sbyte* name, ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_set_topic_filter(dds_entity_t topic, dds_topic_filter_fn filter);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_topic_set_filter(dds_entity_t topic, dds_topic_filter_fn filter);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_set_topic_filter_and_arg(dds_entity_t topic, dds_topic_filter_arg_fn filter, void* arg);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_set_topic_filter_extended(dds_entity_t topic, dds_topic_filter* filter);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_topic_filter_fn dds_get_topic_filter(dds_entity_t topic);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_topic_filter_fn dds_topic_get_filter(dds_entity_t topic);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_topic_filter_and_arg(dds_entity_t topic, dds_topic_filter_arg_fn* fn, void* * arg);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_topic_filter_extended(dds_entity_t topic, dds_topic_filter* filter);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_subscriber(dds_entity_t participant, dds_qos_t* qos, dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_publisher(dds_entity_t participant, dds_qos_t* qos, dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_suspend(dds_entity_t publisher);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_resume(dds_entity_t publisher);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_wait_for_acks(dds_entity_t publisher_or_writer, dds_duration_t timeout);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_reader(dds_entity_t participant_or_subscriber, dds_entity_t topic, dds_qos_t* qos, dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_reader_rhc(dds_entity_t participant_or_subscriber, dds_entity_t topic, dds_qos_t* qos, dds_listener_t* listener, dds_rhc* rhc);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_reader_wait_for_historical_data(dds_entity_t reader, dds_duration_t max_wait);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_writer(dds_entity_t participant_or_publisher, dds_entity_t topic, dds_qos_t* qos, dds_listener_t* listener);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_register_instance(dds_entity_t writer, dds_instance_handle_t* handle, void* data);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_unregister_instance(dds_entity_t writer, void* data);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_unregister_instance_ih(dds_entity_t writer, dds_instance_handle_t handle);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_unregister_instance_ts(dds_entity_t writer, void* data, dds_time_t timestamp);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_unregister_instance_ih_ts(dds_entity_t writer, dds_instance_handle_t handle, dds_time_t timestamp);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_writedispose(dds_entity_t writer, void* data);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_writedispose_ts(dds_entity_t writer, void* data, dds_time_t timestamp);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_dispose(dds_entity_t writer, void* data);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_dispose_ts(dds_entity_t writer, void* data, dds_time_t timestamp);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_dispose_ih(dds_entity_t writer, dds_instance_handle_t handle);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_dispose_ih_ts(dds_entity_t writer, dds_instance_handle_t handle, dds_time_t timestamp);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_write(dds_entity_t writer, void* data);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_write_flush(dds_entity_t writer);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_writecdr(dds_entity_t writer, ddsi_serdata* serdata);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_forwardcdr(dds_entity_t writer, ddsi_serdata* serdata);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_write_ts(dds_entity_t writer, void* data, dds_time_t timestamp);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_readcondition(dds_entity_t reader, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_querycondition(dds_entity_t reader, uint mask, dds_querycondition_filter_fn filter);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_guardcondition(dds_entity_t participant);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_set_guardcondition(dds_entity_t guardcond, CBool triggered);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_guardcondition(dds_entity_t guardcond, CBool* triggered);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_guardcondition(dds_entity_t guardcond, CBool* triggered);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_create_waitset(dds_entity_t participant);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_waitset_get_entities(dds_entity_t waitset, dds_entity_t* entities, ulong size);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_waitset_attach(dds_entity_t waitset, dds_entity_t entity, dds_attach_t x);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_waitset_detach(dds_entity_t waitset, dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_waitset_set_trigger(dds_entity_t waitset, CBool trigger);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_waitset_wait(dds_entity_t waitset, dds_attach_t* xs, ulong nxs, dds_duration_t reltimeout);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_waitset_wait_until(dds_entity_t waitset, dds_attach_t* xs, ulong nxs, dds_time_t abstimeout);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, ulong bufsz, uint maxs);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_wl(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, uint maxs);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_mask(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, ulong bufsz, uint maxs, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_mask_wl(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, uint maxs, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_instance(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, ulong bufsz, uint maxs, dds_instance_handle_t handle);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_instance_wl(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, uint maxs, dds_instance_handle_t handle);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_instance_mask(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, ulong bufsz, uint maxs, dds_instance_handle_t handle, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_instance_mask_wl(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, uint maxs, dds_instance_handle_t handle, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, ulong bufsz, uint maxs);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_wl(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, uint maxs);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_mask(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, ulong bufsz, uint maxs, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_mask_wl(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, uint maxs, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_readcdr(dds_entity_t reader_or_condition, ddsi_serdata* * buf, uint maxs, dds_sample_info_t* si, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_takecdr(dds_entity_t reader_or_condition, ddsi_serdata* * buf, uint maxs, dds_sample_info_t* si, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_instance(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, ulong bufsz, uint maxs, dds_instance_handle_t handle);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_instance_wl(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, uint maxs, dds_instance_handle_t handle);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_instance_mask(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, ulong bufsz, uint maxs, dds_instance_handle_t handle, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_instance_mask_wl(dds_entity_t reader_or_condition, void* * buf, dds_sample_info_t* si, uint maxs, dds_instance_handle_t handle, uint mask);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_next(dds_entity_t reader, void* * buf, dds_sample_info_t* si);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_take_next_wl(dds_entity_t reader, void* * buf, dds_sample_info_t* si);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_next(dds_entity_t reader, void* * buf, dds_sample_info_t* si);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_read_next_wl(dds_entity_t reader, void* * buf, dds_sample_info_t* si);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_return_loan(dds_entity_t reader_or_condition, void* * buf, int bufsz);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_instance_handle_t dds_lookup_instance(dds_entity_t entity, void* data);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_instance_handle_t dds_instance_lookup(dds_entity_t entity, void* data);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_instance_get_key(dds_entity_t entity, dds_instance_handle_t inst, void* data);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_begin_coherent(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_end_coherent(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_notify_readers(dds_entity_t subscriber);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_triggered(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_entity_t dds_get_topic(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_matched_subscriptions(dds_entity_t writer, dds_instance_handle_t* rds, ulong nrds);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_builtintopic_endpoint_t* dds_get_matched_subscription_data(dds_entity_t writer, dds_instance_handle_t ih);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_get_matched_publications(dds_entity_t reader, dds_instance_handle_t* wrs, ulong nwrs);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_builtintopic_endpoint_t* dds_get_matched_publication_data(dds_entity_t reader, dds_instance_handle_t ih);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_builtintopic_free_endpoint(dds_builtintopic_endpoint_t* builtintopic_endpoint);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void dds_builtintopic_free_participant(dds_builtintopic_participant_t* builtintopic_participant);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_assert_liveliness(dds_entity_t entity);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
    public static extern dds_return_t dds_domain_set_deafmute(dds_entity_t entity, CBool deaf, CBool mute, dds_duration_t reset_after);

    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 8)]
    public struct ddsrt_wctime_t
    {
        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_time_t v;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 8)]
    public struct ddsrt_mtime_t
    {
        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_time_t v;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 8)]
    public struct ddsrt_etime_t
    {
        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_time_t v;
    }

    [StructLayout(LayoutKind.Explicit, Size = 88, Pack = 8)]
    public struct ddsrt_log_cfg
    {
        [FieldOffset(0)] /* size = 12, padding = 0 */
        public ddsrt_log_cfg_common c;

        [FieldOffset(0)] /* size = 72, padding = 0 */
        public Anonymous_Union_ddsrt_log_cfg u;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56, Pack = 8)]
    public struct dds_topic_descriptor_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint m_size;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint m_align;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint m_flagset;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint m_nkeys;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public sbyte* m_typename;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_key_descriptor_t* m_keys;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint m_nops;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public uint* m_ops;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public sbyte* m_meta;
    }

    [StructLayout(LayoutKind.Explicit, Size = -2, Pack = -2)]
    public struct dds_qos_t
    {
    }

    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct dds_inconsistent_topic_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24, Pack = 8)]
    public struct dds_publication_matched_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint current_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int current_count_change;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_instance_handle_t last_subscription_handle;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct dds_liveliness_lost_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16, Pack = 8)]
    public struct dds_offered_deadline_missed_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_instance_handle_t last_instance_handle;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12, Pack = 4)]
    public struct dds_offered_incompatible_qos_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint last_policy_id;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24, Pack = 8)]
    public struct dds_subscription_matched_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint current_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int current_count_change;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_instance_handle_t last_publication_handle;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24, Pack = 8)]
    public struct dds_liveliness_changed_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint alive_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint not_alive_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int alive_count_change;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int not_alive_count_change;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_instance_handle_t last_publication_handle;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24, Pack = 8)]
    public struct dds_sample_rejected_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public dds_sample_rejected_status_kind last_reason;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_instance_handle_t last_instance_handle;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 4)]
    public struct dds_sample_lost_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16, Pack = 8)]
    public struct dds_requested_deadline_missed_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_instance_handle_t last_instance_handle;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12, Pack = 4)]
    public struct dds_requested_incompatible_qos_status_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint total_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public int total_count_change;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint last_policy_id;
    }

    [StructLayout(LayoutKind.Explicit, Size = -2, Pack = -2)]
    public struct dds_listener_t
    {
    }

    [StructLayout(LayoutKind.Explicit, Size = 16, Pack = 1)]
    public struct dds_guid_t
    {
        [FieldOffset(0)] /* size = 16, padding = 0 */
        public fixed byte v[16]; /* original type is `uint8_t [16]` */
    }

    [StructLayout(LayoutKind.Explicit, Size = -2, Pack = -2)]
    public struct ddsi_config
    {
    }

    [StructLayout(LayoutKind.Explicit, Size = -2, Pack = -2)]
    public struct ddsi_sertype
    {
    }

    [StructLayout(LayoutKind.Explicit, Size = -2, Pack = -2)]
    public struct ddsi_plist
    {
    }

    [StructLayout(LayoutKind.Explicit, Size = -2, Pack = -2)]
    public struct ddsi_sertopic
    {
    }

    [StructLayout(LayoutKind.Explicit, Size = 24, Pack = 8)]
    public struct dds_topic_filter
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public dds_topic_filter_mode mode;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public union dds_topic_filter_function_union  f;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public void* arg;
    }

    [StructLayout(LayoutKind.Explicit, Size = -2, Pack = -2)]
    public struct dds_rhc
    {
    }

    [StructLayout(LayoutKind.Explicit, Size = -2, Pack = -2)]
    public struct ddsi_serdata
    {
    }

    [StructLayout(LayoutKind.Explicit, Size = 64, Pack = 8)]
    public struct dds_sample_info_t
    {
        [FieldOffset(0)] /* size = 4, padding = 0 */
        public dds_sample_state_t sample_state;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public dds_view_state_t view_state;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public dds_instance_state_t instance_state;

        [FieldOffset(0)] /* size = 1, padding = 0 */
        public CBool valid_data;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_time_t source_timestamp;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_instance_handle_t instance_handle;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_instance_handle_t publication_handle;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint disposed_generation_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint no_writers_generation_count;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint sample_rank;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint generation_rank;

        [FieldOffset(0)] /* size = 4, padding = 0 */
        public uint absolute_generation_rank;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64, Pack = 8)]
    public struct dds_builtintopic_endpoint_t
    {
        [FieldOffset(0)] /* size = 16, padding = 0 */
        public dds_guid_t key;

        [FieldOffset(0)] /* size = 16, padding = 0 */
        public dds_guid_t participant_key;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_instance_handle_t participant_instance_handle;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public sbyte* topic_name;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public sbyte* type_name;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_qos_t* qos;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24, Pack = 8)]
    public struct dds_builtintopic_participant_t
    {
        [FieldOffset(0)] /* size = 16, padding = 0 */
        public dds_guid_t key;

        [FieldOffset(0)] /* size = 8, padding = 0 */
        public dds_qos_t* qos;
    }

    public enum dds_free_op_t : uint
    {
        DDS_FREE_ALL = 7U,
        DDS_FREE_CONTENTS = 3U,
        DDS_FREE_KEY = 1U
    }

    public enum dds_durability_kind_t : uint
    {
        DDS_DURABILITY_VOLATILE = 0U,
        DDS_DURABILITY_TRANSIENT_LOCAL = 1U,
        DDS_DURABILITY_TRANSIENT = 2U,
        DDS_DURABILITY_PERSISTENT = 3U
    }

    public enum dds_history_kind_t : uint
    {
        DDS_HISTORY_KEEP_LAST = 0U,
        DDS_HISTORY_KEEP_ALL = 1U
    }

    public enum dds_presentation_access_scope_kind_t : uint
    {
        DDS_PRESENTATION_INSTANCE = 0U,
        DDS_PRESENTATION_TOPIC = 1U,
        DDS_PRESENTATION_GROUP = 2U
    }

    public enum dds_ownership_kind_t : uint
    {
        DDS_OWNERSHIP_SHARED = 0U,
        DDS_OWNERSHIP_EXCLUSIVE = 1U
    }

    public enum dds_liveliness_kind_t : uint
    {
        DDS_LIVELINESS_AUTOMATIC = 0U,
        DDS_LIVELINESS_MANUAL_BY_PARTICIPANT = 1U,
        DDS_LIVELINESS_MANUAL_BY_TOPIC = 2U
    }

    public enum dds_reliability_kind_t : uint
    {
        DDS_RELIABILITY_BEST_EFFORT = 0U,
        DDS_RELIABILITY_RELIABLE = 1U
    }

    public enum dds_destination_order_kind_t : uint
    {
        DDS_DESTINATIONORDER_BY_RECEPTION_TIMESTAMP = 0U,
        DDS_DESTINATIONORDER_BY_SOURCE_TIMESTAMP = 1U
    }

    public enum dds_ignorelocal_kind_t : uint
    {
        DDS_IGNORELOCAL_NONE = 0U,
        DDS_IGNORELOCAL_PARTICIPANT = 1U,
        DDS_IGNORELOCAL_PROCESS = 2U
    }

    public enum dds_type_consistency_kind_t : uint
    {
        DDS_TYPE_CONSISTENCY_DISALLOW_TYPE_COERCION = 0U,
        DDS_TYPE_CONSISTENCY_ALLOW_TYPE_COERCION = 1U
    }
}