// Copyright (c) Bottlenose Labs Inc. (https://github.com/bottlenoselabs). All rights reserved.
// Licensed under the MIT license. See LICENSE file in the Git repository root directory for full license information.

namespace C2CS.GenerateCSharpCode;

public sealed class CodeGeneratorDocumentAssemblyAttributes
{
    public CodeProjectDocument Generate(CodeGeneratorDocumentOptions options)
    {
        var code = $"""
                    // <auto-generated>
                    //  This code was generated by the following tool on {options.DateTimeStamp}:
                    //      https://github.com/bottlenoselabs/c2cs (v{options.VersionStamp})
                    //
                    //  Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                    // </auto-generated>
                    // ReSharper disable All

                    using System.Runtime.CompilerServices;
                    using System.Runtime.InteropServices;

                    """;

        if (!options.IsEnabledRuntimeMarshalling)
        {
            code += """

                    #if NET7_0_OR_GREATER
                    // NOTE: Disabling runtime marshalling is preferred for performance improvements. You can learn more here: https://learn.microsoft.com/en-us/dotnet/standard/native-interop/disabled-marshalling
                    [assembly: DisableRuntimeMarshalling]
                    #endif

                    """;
        }

        code += """

                #if (NETCOREAPP1_0_OR_GREATER) || (NET45_OR_GREATER || NETFRAMEWORK && (NET45 || NET451 || NET452 || NET46 || NET461 || NET462 || NET47 || NET471 || NET472 || NET48)) || (NETSTANDARD1_1_OR_GREATER || NETSTANDARD && !NETSTANDARD1_0)
                // NOTE: Only takes effect on Windows. Specifies the recommended maximum number of directories (the application directory, the %WinDir%\System32 directory, and user directories in the DLL search path) to search for native libraries. You can learn more here at (1) https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.defaultdllimportsearchpathsattribute and (2) https://learn.microsoft.com/en-ca/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexa#parameters
                [assembly: DefaultDllImportSearchPathsAttribute(DllImportSearchPath.SafeDirectories)]
                #endif

                """;

        var document = new CodeProjectDocument
        {
            FileName = "AssemblyAttributes.g.cs",
            Code = code
        };

        return document;
    }
}
